name: Format Code

on:
  push:
    branches: [main]
  pull_request:
    branches-ignore: [main]

permissions:
  checks: write
  contents: write

jobs:
  build:
    name: Format Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Auto-Formatter
      uses: mezgoodle/auto-formatter@v1.0.2
      env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
